Numpy Array and basics

In [2]:
import numpy as np 
a=np.array([10,20,30])
print(a)

[10 20 30]


Array Creation

In [3]:
d1=np.array([10,20,30])
d2=np.array([10,20,30])
print(d1+d2)

[20 40 60]


Array V/S List

In [5]:
import time as t
# List
start=t.time()
list_time=[ i*2 for i in range(1000000)]
end=t.time()
print("List operation",end-start)

# Numpy array
s=t.time()
array_time=np.arange(1000000)*2
e=t.time()
print("Array operation",e-s)

List operation 0.034028053283691406
Array operation 0.0012857913970947266


Creating Array From Scratch

In [ ]:
# Zero matrix
zeros=np.zeros((2,3))
print(zeros)

# One's matrix
one=np.ones((2,3))
print(one)

#Full ( creating a matrix appart from 0 and 1)
seven=np.full((3,3),7)  # use other numbers in place of 7 to print another numbers matrix 
print(seven)

#Random
random=np.random.random((2,2))
print(random)   # the values in matrix will be in a range from 0 - 1

#Sequence start,stop,step
sequence=np.arange(10,31,2)         # 10=start. 31=stop. 2=step
print("Sequence of 10 to 30",sequence)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[7 7 7]
 [7 7 7]
 [7 7 7]]
[[0.20152258 0.23699858]
 [0.69325771 0.23381933]]
Sequence of 10 to 30 [10 12 14 16 18 20 22 24 26 28 30]


Vector,Matrix and Tensor

In [23]:
vector=np.array([10,20,30,40,50])
print("vector:\n",vector,"\n")

matrix=np.array([[10,20,30],
                 [40,50,60]])
print("matrix:\n",matrix,"\n")

tensor=np.array([
    [[1,2,3,],[2,3,4]],
    [[1,2,3],[4,5,6]]
])
print("tensor:\n",tensor)

vector:
 [10 20 30 40 50] 

matrix:
 [[10 20 30]
 [40 50 60]] 

tensor:
 [[[1 2 3]
  [2 3 4]]

 [[1 2 3]
  [4 5 6]]]


Array Properties

In [ ]:
arr=np.array([[1,2,3],[3,4,5]])
print("Shape:",arr.shape)   # number of rows and columns
print("Dimension:",arr.ndim) # Dimension of the array
print("Size:",arr.size)       # total number of elemnets
print("Data Type:",arr.dtype) # returns data type used


Shape: (2, 3)
Dimension: 2
Size: 6
Data Type: int64


Array Reshaping

In [35]:
arr=np.arange(12)
print(arr,"\n")
reshape=arr.reshape((3,4))   # formating of array into 3X4 matrix
print(reshape,"\n")     
mat=np.array([[10,20,0],
              [220,40,90]])
f1=mat.flatten()
print(f1)

[ 0  1  2  3  4  5  6  7  8  9 10 11] 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

[ 10  20   0 220  40  90]
