Numpy Array Operation|

In [2]:
import numpy as np

Slicing

In [ ]:
arr=np.array([10,20,30])
print("Basic slicing",arr[:4])
print("positive indexing",arr[0:2:2])
print("negative indexing",arr[-1])

Basic slicing [10 20 30]
positive indexing [10]
negative indexing 30


Accessing Elements using Index

In [23]:
arr_2d=np.array([[1,2,3],
                [3,4,5],
                [7,8,9]])
print("specific element\n",arr_2d[1,2])   #specific element 5
print("entire row\n",arr_2d[1,:])          #entire row [3 4 5]
print("entire column\n",arr_2d[:,1])   #entire column [2 4 8]
print("\n")   
print(arr_2d[1:,2])                     #from row 1 till end row print element at index 2 of that perticular row [5 9]
print("\n")
print(arr_2d[1:,1:])                    #rom row 1 till end row print element from index 1 till end of that perticular row [[4 5][8 9]] 

specific element
 5
entire row
 [3 4 5]
entire column
 [2 4 8]


[5 9]


[[4 5]
 [8 9]]


Sorting

In [31]:
#1-D
arr_1d=np.array([1,2,3,4,5])
print("Sorting",sorted(arr_1d))         #Sorting [np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5)] with datatype
print("Sorting",np.sort(arr_1d))        #Sorting [1 2 3 4 5]

#2-D
arr_2d=np.array([[2,2,3],
                [3,4,3],
                [7,1,9]])
print("2d sorting",np.sort(arr_2d))         # sorting row wise 
arr_2d=np.array([[2,2,9],
                [3,4,3],
                [7,4,9]])
print("2d sorting",np.sort(arr_2d,axis=0))   # sorting column wise

# axis=1 row axis=0 column

Sorting [np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5)]
Sorting [1 2 3 4 5]
2d sorting [[2 2 3]
 [3 3 4]
 [1 7 9]]
2d sorting [[2 2 3]
 [3 4 9]
 [7 4 9]]


Filter

In [ ]:
n=np.array([1,2,3,4,5,6,7,8,10])
even=n[n%2==0]
print(even)             # printing even numbers from the list without looping 

[ 2  4  6  8 10]


Filter with mask

In [34]:
marks=np.array([10,20,30,40,50])
mark_pass= marks>35
print(mark_pass)

[False False False  True  True]


Index

In [3]:
sales=np.array([9000,5000,1000,78900,780])
indx=[1,3]
res=sales[indx]
print(res)

[ 5000 78900]
