Numpy Array Operation|

In [2]:
import numpy as np

Slicing

In [ ]:
arr=np.array([10,20,30])
print("Basic slicing",arr[:4])
print("positive indexing",arr[0:2:2])
print("negative indexing",arr[-1])

Basic slicing [10 20 30]
positive indexing [10]
negative indexing 30


Accessing Elements using Index

In [23]:
arr_2d=np.array([[1,2,3],
                [3,4,5],
                [7,8,9]])
print("specific element\n",arr_2d[1,2])   #specific element 5
print("entire row\n",arr_2d[1,:])          #entire row [3 4 5]
print("entire column\n",arr_2d[:,1])   #entire column [2 4 8]
print("\n")   
print(arr_2d[1:,2])                     #from row 1 till end row print element at index 2 of that perticular row [5 9]
print("\n")
print(arr_2d[1:,1:])                    #rom row 1 till end row print element from index 1 till end of that perticular row [[4 5][8 9]] 

specific element
 5
entire row
 [3 4 5]
entire column
 [2 4 8]


[5 9]


[[4 5]
 [8 9]]


Sorting

In [31]:
#1-D
arr_1d=np.array([1,2,3,4,5])
print("Sorting",sorted(arr_1d))         #Sorting [np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5)] with datatype
print("Sorting",np.sort(arr_1d))        #Sorting [1 2 3 4 5]

#2-D
arr_2d=np.array([[2,2,3],
                [3,4,3],
                [7,1,9]])
print("2d sorting",np.sort(arr_2d))         # sorting row wise 
arr_2d=np.array([[2,2,9],
                [3,4,3],
                [7,4,9]])
print("2d sorting",np.sort(arr_2d,axis=0))   # sorting column wise

# axis=1 row axis=0 column

Sorting [np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5)]
Sorting [1 2 3 4 5]
2d sorting [[2 2 3]
 [3 3 4]
 [1 7 9]]
2d sorting [[2 2 3]
 [3 4 9]
 [7 4 9]]


Filter

In [ ]:
n=np.array([1,2,3,4,5,6,7,8,10])
even=n[n%2==0]
print(even)             # printing even numbers from the list without looping 

[ 2  4  6  8 10]


Filter with mask

In [34]:
marks=np.array([10,20,30,40,50])
mark_pass= marks>35
print(mark_pass)

[False False False  True  True]


Fancy Index

In [3]:
sales=np.array([9000,5000,1000,78900,780])
indx=[1,3]
res=sales[indx]
print(res)

[ 5000 78900]


JOIN

In [10]:
# combining 1D array
a1=np.array([1,2,3,4,5])
a2=np.array([10,20,30,40,50])
combined=np.concat([a1,a2])
print("Combined:",combined)

# combining 2D array
a21=np.array([[10,20],
             [30,40]])
a22=np.array([[50,60],[70,80]])

#vertical join i.e 4 x 2
print("join vertical:",np.vstack([a21,a22]))
#output:
#join horizontal: [[10 20]
 #[30 40]
 #[50 60]
 #[70 80]]


#horizontal join i.e 2 x 4
print("join horizontal:",np.hstack([a21,a22]))
# output:
#join horizontal:
#[[10 20 50 60]
 #[30 40 70 80]]




Combined: [ 1  2  3  4  5 10 20 30 40 50]
join vertical: [[10 20]
 [30 40]
 [50 60]
 [70 80]]
join horizontal: [[10 20 50 60]
 [30 40 70 80]]


Adding and Removing

In [ ]:
arr=np.array([10,20,30,40,50,60])   
print("Split:",np.split(arr,2)) #number of elemnets should be even to use split

print("Append",np.append(arr,50))   #immutable so changes made are temporary op:Append [10 20 30 40 50 60 50]
print("org:",arr)   # op:org: [10 20 30 40 50 60]

print("insert:",np.insert(arr,0,20))    # syntax:.insert(name,index,element) op:insert: [20 10 20 30 40 50 60]
print("org:",arr)   # op:org: [10 20 30 40 50 60]

print("delete:",np.delete(arr,2))    # syntax:.insert(name,index) op:delete: [10 20 40 50 60]
print("org:",arr)   # op:org: [10 20 30 40 50 60]

Split: [array([10, 20, 30]), array([40, 50, 60])]
Append [10 20 30 40 50 60 50]
org: [10 20 30 40 50 60]
insert: [20 10 20 30 40 50 60]
org: [10 20 30 40 50 60]
delete: [10 20 40 50 60]
org: [10 20 30 40 50 60]


Task 1 : How to apply adding and removing in 2D in numpy matrix ? 
Task 2 : Check mathematical operation in numpy (add,sub,mul,div,pow,sq root)

In [ ]:
a1=np.array([[1,2,3,4,5],
             [1,2,3,4,5]])
a2=np.array([[10,20,30,40,50],
             [10,20,30,40,50]])

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print("Original Matrix:")
print(arr)

# Add a row
arr = np.vstack((arr, [7, 8, 9]))
print("\nAfter adding a row:")
print(arr)

# Add a column
arr = np.column_stack((arr, [10, 11, 12]))
print("\nAfter adding a column:")
print(arr)

# Remove a row
arr = np.delete(arr, 1, axis=0)
print("\nAfter removing row 1:")
print(arr)

# Remove a column
arr = np.delete(arr, 2, axis=1)
print("\nAfter removing column 2:")
print(arr)


[[11 22 33 44 55]
 [11 22 33 44 55]]
Original Matrix:
[[1 2 3]
 [4 5 6]]

After adding a row:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

After adding a column:
[[ 1  2  3 10]
 [ 4  5  6 11]
 [ 7  8  9 12]]

After removing row 1:
[[ 1  2  3 10]
 [ 7  8  9 12]]

After removing column 2:
[[ 1  2 10]
 [ 7  8 12]]


In [3]:
a=np.array([[1,2,3,4,5],
             [1,2,3,4,5]])
b=np.array([[10,20,30,40,50],
             [10,20,30,40,50]])
print("Addition:")
print(a + b)

print("Subtraction:")
print(a - b)

print("Multiplication:")
print(a * b)

print("Division:")
print(a / b)

print("Power:")
print(np.power(a, 2))

print("Square Root:")
print(np.sqrt(a))

Addition:
[[11 22 33 44 55]
 [11 22 33 44 55]]
Subtraction:
[[ -9 -18 -27 -36 -45]
 [ -9 -18 -27 -36 -45]]
Multiplication:
[[ 10  40  90 160 250]
 [ 10  40  90 160 250]]
Division:
[[0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1]]
Power:
[[ 1  4  9 16 25]
 [ 1  4  9 16 25]]
Square Root:
[[1.         1.41421356 1.73205081 2.         2.23606798]
 [1.         1.41421356 1.73205081 2.         2.23606798]]


In [5]:
sales_data = np.array([
    [1, 150000, 180000, 220000, 250000],
    [2, 120000, 140000, 160000, 190000],
    [3, 200000, 230000, 260000, 300000],
    [4, 180000, 210000, 240000, 270000],
    [5, 160000, 185000, 205000, 230000]
])
print("Shape:", sales_data.shape)
print("First 3 restaurants:")
print(sales_data[:3])
print("Total sale per year:")
print(np.sum(sales_data[:, 1:], axis=0))
print("Maximum sale per restaurant:")
print(np.max(sales_data[:, 1:], axis=1))
print("Maximum sale every year:")
print(np.max(sales_data[:, 1:], axis=0))
print("Average sale per restaurant:")
print(np.mean(sales_data[:, 1:], axis=1))
print("Average cumulative sale:")
print(np.mean(sales_data[:, 1:]))
print("Average sale every year:")
print(np.mean(sales_data[:, 1:], axis=0))

Shape: (5, 5)
First 3 restaurants:
[[     1 150000 180000 220000 250000]
 [     2 120000 140000 160000 190000]
 [     3 200000 230000 260000 300000]]
Total sale per year:
[ 810000  945000 1085000 1240000]
Maximum sale per restaurant:
[250000 190000 300000 270000 230000]
Maximum sale every year:
[200000 230000 260000 300000]
Average sale per restaurant:
[200000. 152500. 247500. 225000. 195000.]
Average cumulative sale:
204000.0
Average sale every year:
[162000. 189000. 217000. 248000.]
